site_name: Ckeditor Json
site_description: A customized build of CKEditor, a rich text editor, for generating output valid for json-to-pdf backend java library.
site_author: Indra - jarey@minsait.com
site_url: https://gitlab.com/jarey/ckeditor-json

docs_dir: doc
site_dir: web

repo_name: Gitlab
repo_url: https://gitlab.com/jarey/ckeditor-json
edit_uri: ''

copyright: Copyright &copy; Indra
google_analytics:
- !!python/object/apply:os.getenv [GOOGLE_ANALYTICS_ID]
- auto

markdown_extensions:
- admonition
- codehilite
- meta

nav:
- Overview: index.md
- Installation: installation.md
- Usage: usage.md
- About:
  - Changelog: about/changelog.md
  - License: about/license.md
  - See also: about/see_also.md

theme:
  name: material
  favicon: img/favicon.ico
  palette: {primary: yellow, accent: yellow}
